M48
; DRILL file {KiCad (6.0.2-0)} date Tuesday, May 31, 2022 at 09:56:36 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-31T21:56:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X143.332Y-64.516
X143.332Y-92.862
X169.697Y-64.516
X169.697Y-92.862
T0
M30
